# Generated by Django 5.2.4 on 2025-07-28 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Заполняется автоматически, но может быть изменена вручную",
                verbose_name="Дата создания записи",
            ),
        ),
    ]
